FROM python:3.9-slim-bullseye
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


COPY api/requirements.txt .
RUN pip install -r requirements.txt

COPY api ./api


ENV RESSOURCESPATH "/app/api/model/ressources/"
EXPOSE 3000
WORKDIR /app/api
CMD ["gunicorn", "-b", ":5000", "api:app"]

