services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-app-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"
    volumes:
      - .:/app
